### ISSUE TITLE
MsgFontBoldSize / ZB Command Unimplemented

### ISSUE THREAD

**Issue by RottenBlock** [kichikuou/xsystem35-sdl2#44] opened 2024-01-15 06:56 UTC
### Environment
 - xsystem35 version: 2.10.1

SupremeJUMBO at the wiki noticed that the ZB command doesn't seem to be working right now. Looking into it, it sets the variable MsgFontBoldSize, but unfortunately, the variable is never actually used when rendering text - just by the ZB command itself. The command apparently does work in System 3.9.

**Comment by kichikuou** [comment] 2024-01-16 03:26
I believe the argument of `ZB` command is multiplied by 100 and used as the value of [`lfWeight`](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-logfonta#:~:text=of%20the%20device.-,lfWeight,-The%20weight%20of) of Windows `LOGFONT` struct.

System3.9 with MS Gothic font behave as follows:

![ALCG0000](https://github.com/kichikuou/xsystem35-sdl2/assets/12679772/3478d5c5-db68-44b0-82ac-c4a7f10a992f)

MS Gothic has only two weights[^1], so it is rendered in bold with `ZB 6` or higher. Note that the default value of `ZB` is 7, which is bold.

If we implement this faithfully in xsystem35, we would use [`TTF_SetFontStyle`](https://wiki.libsdl.org/SDL2_ttf/TTF_SetFontStyle) with `TTF_STYLE_BOLD` when `ZB` is 6 or more. Trying it with `MTLc3m.ttf` (our default font) gives the following result:

![xsystem35](https://github.com/kichikuou/xsystem35-sdl2/assets/12679772/b37b6132-a139-4ab1-8e1c-5a909141ef0d)

The default `ZB 7` looks too heavy, especially at larger sizes. This is more obvious when you see it in the actual game screen:

![KR](https://github.com/kichikuou/xsystem35-sdl2/assets/12679772/d6ed3dad-a636-4c9d-a2df-0d062e0d880f)

Another problem is that `TTF_SetFontStyle` affects text width, while System3.9 does not. This may break the layout.

[^1]: Actually, MS Gothic has only one weight, and the bold version is synthesized by the font rendering engine.

### Why is it like this?

For small sizes, MS Gothic uses bitmap glyphs with 1-pixel thick. This is too thin, so they may have made `ZB 7` the default.
Modern vector fonts (including `MTLc3m.ttf`) have a slightly thicker regular weight, so it probably makes more sense not to default to bold.

### What should we do?

The following is just a list of possible solutions; the order is not meaningful.

- Enable embolding with `ZB 6` or higher, and change the default font to a lighter one.

  For copyright reasons, we cannot bundle MS Gothic. `MTLc3m.ttf` has some nice properties (small file size, monospaced, ASCII characters are exactly half the width of full-width characters, etc.), and there are not many fonts that can be an alternative.

- Enable embolding with `ZB 6` or higher, but only when enabled by a flag in `.xsys35rc`.

  Game/mod authors who want to take advantage of the `ZB` command can enable it explicitly. They may also want to bundle font files with their distributions. In a sense, this is similar to the above, but puts the burden of font selection on the game/mod author.

- Improve the font emboldening algorithm.

  More modest emboldening might be possible by using the Freetype library directly instead of via SDL_ttf. This would be a somewhat large change.

- Do nothing.

  Any of the above implies using bold text by default (`ZB 7`). Generally, the quality of synthesized bold is not great.

Comments and suggestions are welcome!

**Comment by RottenBlock** [comment] 2024-01-16 07:35
I'm personally inclined towards the .xsys35 option, so long as we aren't worried about the look of official Alicesoft games.

For the record, these are the English games that use the ZB command. I did check several Japanese games that I have on hand but I don't have all of them. One of these days I need to make a searchable directory.

- Kichikuou Rance
- Mamatoto
- Only You Re Cross
- Gakuen Drifting Story 2

**Comment by kichikuou** [comment] 2024-01-16 12:53
I do have a collection of ADV files from almost all AliceSoft System 3.x games and some indie games, for regression testing of xsys35c.

Below is a list of games that use the ZB command. (I often do this kind of query to find out the impact of code changes.)

- DARCROWS
- 鬼畜王ランス
- 夜が来る！
- ママトト
- ぱすてるチャイム
- SeeIn青
- Only You -リ・クルス-
- 大悪司
- 王子さまLv1.5
- 戦巫女
- 隠れ月
- これD・P・S？ (20世紀アリス)
- メイドのススメ (AliceCD)
- ぶろぶろ (AliceCD)
- 妄想くん (AliceCD)
- 当たって!!KUDAKERO (AliceCD)
- 学園漂流戦記２ (AliceCD)
- できるかなー！ (AliceCD)
- 眼鏡大戦２ (AliceCD)
- グレイメルカ (indie)

I don't know if in any of these cases the ZB command is used to convey some information rather than just to improve the appearance.

**Comment by SupremeJUMBO** [comment] 2024-01-16 23:52
Hello, I'm a big fan of your work! I agree that the simplest solution is to just have a flag in .xsys35rc. I'm not even sure if I'll end up needing the wider font, it was just something I noticed since I was originally using ZB to shrink the font width in the system39 version.

**Comment by kichikuou** [comment] 2024-01-18 02:17
Thanks for the comment. I have implemented the `.xsys35rc` solution.

In the game directory put `.xsys35rc` file with
```
enable_zb: Yes
```
then xsystem35 will respect the `ZB` command.

This will be included in the next release, but if you want to try it out right away you can download a Windows binary [here](https://github.com/kichikuou/xsystem35-sdl2/actions/runs/7564343802). (Note: The debugger is now supported only on 64-bit build.)

If you decide to actually use this feature, please let me know. I will stabilize this feature and make sure that its behavior does not change. In the meantime, consider this an experimental feature and the behavior may be changed if a better solution is found.

**Comment by SupremeJUMBO** [comment] 2024-01-18 06:30
Thanks, I appreciate it! Never hurts to have more modding tools available in case I need them. The game runs so much faster and smoother on xsystem35, you did a phenomenal job.

**Closed** 2024-01-20 06:02 UTC

**Comment by kichikuou** [comment] 2026-09-06 07:40
Update: The font rendering has been reworked. Changes since the last update:

- Font rendering now uses FreeType directly instead of SDL_ttf, with a [synthetic bold algorithm](https://github.com/kichikuou/xsystem35-sdl2/blob/253de6adc817481cd3d3f9b7713f8452f22a297b/src/font.c#L190-L212) close to the one GDI uses. This no longer changes the text width, so layouts are preserved.
- The `ZB` command is now always enabled. The experimental `enable_zb` option has been removed.
- On Windows, MS Gothic / MS Mincho are used by default when installed, in preference to the bundled fonts.
  - If they are not present on your system, you can install them via **Settings → System → Optional features → View features**, then search for **Japanese Supplemental Fonts**. See [this article](https://learn.microsoft.com/en-us/windows/deployment/windows-missing-fonts) for details.

These changes will be included in the next release (v2.20.0). To try them now, you can download a Windows build from [this CI run](https://github.com/kichikuou/xsystem35-sdl2/actions/runs/34018546426) (GitHub login required).
